### PR TITLE
Fixing bug with column and header mismatch in hypercube builder

### LINKED ISSUE #262: Hypercube mismatch in header and column
When adding a column which has no values, the data will be fetched with wrong index in the qmatrix. This results in a hypercube in the ui with wrong data to the column header.

### PR DESCRIPTION
**Pull request by hrigner**
Resolves #262

### CODE REVIEW

File: src/components/hypercube-table.jsx [hunk 1]
```diff
@@ -8,29 +8,31 @@ import useResolvedValue from './use/resolved-value';
 
 import './hypercube-table.pcss';
 
-function cellGetterForIndex(index) {
+function cellGetterForIndex(index, layout) {
   return function cellGetter({ rowData }) {
-    if (!rowData || !rowData[index]) {
+    const indexInQMatrix = layout.qHyperCube.qEffectiveInterColumnSortOrder.indexOf(index);
```
Comment (gabbaxx) [inline src/components/hypercube-table.jsx]: Can we move this out to the outer close as this gets called for every cell rendered and the indexInQMatrix won't change?

File: src/components/hypercube-table.jsx [hunk 2]
```diff
@@ -8,29 +8,31 @@ import useResolvedValue from './use/resolved-value';
...
-    return rowData[index].qText;
+    return rowData[indexInQMatrix].qText;
   };
 }
 
-function cellRendererForIndex(index) {
+function cellRendererForIndex(index, layout) {
   function cellRenderer({ rowData }) {
-    if (!rowData || !rowData[index]) {
+    const indexInQMatrix = layout.qHyperCube.qEffectiveInterColumnSortOrder.indexOf(index);
```
Comment (gabbaxx) [inline src/components/hypercube-table.jsx]: Same as above. Move out to outer closure

File: src/components/hypercube-table.jsx (hunk 1 above)
Comment (hrigner) [reply src/components/hypercube-table.jsx]: ah, of course :)
